/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface CalendarEvent {
  all_day: Generated<boolean | null>;
  color: Generated<string>;
  created_at: Generated<Timestamp>;
  created_by: string;
  description: string | null;
  end_date: Timestamp;
  id: string;
  organization_id: string;
  place_address: string | null;
  place_lat: number | null;
  place_lng: number | null;
  place_name: string | null;
  start_date: Timestamp;
  title: string;
  type: string | null;
  updated_at: Generated<Timestamp | null>;
  updated_by: string | null;
}

export interface File {
  created_at: Generated<Timestamp | null>;
  event_id: string | null;
  filename: string;
  folder_id: string | null;
  id: string;
  kind: string;
  mime_type: string;
  organization_id: string;
  original_filename: string;
  s3_key: string;
  size_bytes: number;
  song_id: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp | null>;
  uploaded_by: string;
}

export interface Folder {
  created_at: Generated<Timestamp | null>;
  id: string;
  name: string;
  organization_id: string;
  parent_folder_id: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface Invitation {
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: string;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
}

export interface Member {
  createdAt: Timestamp;
  id: string;
  organizationId: string;
  role: string;
  userId: string;
}

export interface Organization {
  createdAt: Timestamp;
  createdBy: string | null;
  id: string;
  isPersonal: boolean | null;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface Session {
  activeOrganizationId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface Song {
  artist: string | null;
  bpm: number | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: string;
  key: string | null;
  lyrics: string | null;
  organization_id: string;
  title: string;
  type: string | null;
  updated_at: Generated<Timestamp | null>;
  updated_by: string | null;
}

export interface User {
  banExpires: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  createdAt: Generated<Timestamp>;
  displayUsername: string | null;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  locale: string | null;
  name: string;
  role: string | null;
  theme: string | null;
  updatedAt: Generated<Timestamp>;
  username: string | null;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  calendar_event: CalendarEvent;
  file: File;
  folder: Folder;
  invitation: Invitation;
  member: Member;
  organization: Organization;
  session: Session;
  song: Song;
  user: User;
  verification: Verification;
}
