/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface AudioClip {
  createdAt: Generated<Timestamp>;
  durationMs: number | null;
  fileId: string;
  id: string;
  name: string | null;
  startMeasure: Generated<number>;
  trackId: string;
}

export interface File {
  createdAt: Generated<Timestamp>;
  filename: string;
  id: string;
  organizationId: string;
  storageKey: string;
  type: string;
}

export interface Invitation {
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: string;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
}

export interface Member {
  createdAt: Timestamp;
  id: string;
  organizationId: string;
  role: string;
  userId: string;
}

export interface MidiClip {
  createdAt: Generated<Timestamp>;
  durationMs: number | null;
  fileId: string;
  id: string;
  name: string | null;
  startMeasure: Generated<number>;
  trackId: string;
}

export interface Organization {
  createdAt: Timestamp;
  createdBy: string | null;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface Session {
  activeOrganizationId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface Song {
  bpm: number | null;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  id: string;
  key: string | null;
  name: string;
  organizationId: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
}

export interface SongSectionDefinition {
  chords: Generated<Json>;
  color: string | null;
  createdAt: Generated<Timestamp>;
  id: string;
  lyrics: string | null;
  name: string;
  repeat: Generated<number>;
  songId: string;
  updatedAt: Generated<Timestamp>;
}

export interface SongSectionInstance {
  createdAt: Generated<Timestamp>;
  definitionId: string;
  id: string;
  lengthMeasures: Generated<number>;
  lyricsOverride: string | null;
  repeat: Generated<number>;
  songId: string;
  startMeasure: number;
  updatedAt: Generated<Timestamp>;
}

export interface Track {
  createdAt: Generated<Timestamp>;
  id: string;
  instrumentPreset: number | null;
  name: string;
  order: number;
  songId: string;
  updatedAt: Generated<Timestamp>;
  volume: Generated<number>;
}

export interface User {
  banExpires: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  createdAt: Generated<Timestamp>;
  displayUsername: string | null;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  locale: Generated<string>;
  name: string;
  role: string | null;
  theme: Generated<string>;
  updatedAt: Generated<Timestamp>;
  username: string | null;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  audioClip: AudioClip;
  file: File;
  invitation: Invitation;
  member: Member;
  midiClip: MidiClip;
  organization: Organization;
  session: Session;
  song: Song;
  songSectionDefinition: SongSectionDefinition;
  songSectionInstance: SongSectionInstance;
  track: Track;
  user: User;
  verification: Verification;
}
