/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as CalendarRouteRouteImport } from './routes/calendar/route'
import { Route as OrganizationsRouteRouteImport } from './routes/organizations/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as CalendarEventIdRouteImport } from './routes/calendar/$eventId'
import { Route as OrganizationsOrganizationSlugRouteRouteImport } from './routes/organizations/$organizationSlug/route'
import { Route as OrganizationsNewRouteImport } from './routes/organizations/new'
import { Route as OrganizationsOrganizationSlugIndexRouteImport } from './routes/organizations/$organizationSlug/index'
import { Route as OrganizationsOrganizationSlugCalendarRouteRouteImport } from './routes/organizations/$organizationSlug/calendar/route'
import { Route as OrganizationsOrganizationSlugCalendarIndexRouteImport } from './routes/organizations/$organizationSlug/calendar/index'
import { Route as OrganizationsOrganizationSlugCalendarEventIdRouteImport } from './routes/organizations/$organizationSlug/calendar/$eventId'
import { Route as OrganizationsOrganizationSlugMembersIndexRouteImport } from './routes/organizations/$organizationSlug/members/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRouteRoute = CalendarRouteRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRouteRoute = OrganizationsRouteRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CalendarRouteRoute,
} as any)
const CalendarEventIdRoute = CalendarEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => CalendarRouteRoute,
} as any)
const OrganizationsOrganizationSlugRouteRoute =
  OrganizationsOrganizationSlugRouteRouteImport.update({
    id: '/$organizationSlug',
    path: '/$organizationSlug',
    getParentRoute: () => OrganizationsRouteRoute,
  } as any)
const OrganizationsNewRoute = OrganizationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrganizationsRouteRoute,
} as any)
const OrganizationsOrganizationSlugIndexRoute =
  OrganizationsOrganizationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationsOrganizationSlugRouteRoute,
  } as any)
const OrganizationsOrganizationSlugCalendarRouteRoute =
  OrganizationsOrganizationSlugCalendarRouteRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => OrganizationsOrganizationSlugRouteRoute,
  } as any)
const OrganizationsOrganizationSlugCalendarIndexRoute =
  OrganizationsOrganizationSlugCalendarIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationsOrganizationSlugCalendarRouteRoute,
  } as any)
const OrganizationsOrganizationSlugCalendarEventIdRoute =
  OrganizationsOrganizationSlugCalendarEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => OrganizationsOrganizationSlugCalendarRouteRoute,
  } as any)
const OrganizationsOrganizationSlugMembersIndexRoute =
  OrganizationsOrganizationSlugMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => OrganizationsOrganizationSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRouteRouteWithChildren
  '/organizations': typeof OrganizationsRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/organizations/$organizationSlug': typeof OrganizationsOrganizationSlugRouteRouteWithChildren
  '/calendar/$eventId': typeof CalendarEventIdRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/calendar/': typeof CalendarIndexRoute
  '/organizations/$organizationSlug/calendar': typeof OrganizationsOrganizationSlugCalendarRouteRouteWithChildren
  '/organizations/$organizationSlug/': typeof OrganizationsOrganizationSlugIndexRoute
  '/organizations/$organizationSlug/calendar/$eventId': typeof OrganizationsOrganizationSlugCalendarEventIdRoute
  '/organizations/$organizationSlug/calendar/': typeof OrganizationsOrganizationSlugCalendarIndexRoute
  '/organizations/$organizationSlug/members/': typeof OrganizationsOrganizationSlugMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organizations': typeof OrganizationsRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calendar/$eventId': typeof CalendarEventIdRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/calendar': typeof CalendarIndexRoute
  '/organizations/$organizationSlug': typeof OrganizationsOrganizationSlugIndexRoute
  '/organizations/$organizationSlug/calendar/$eventId': typeof OrganizationsOrganizationSlugCalendarEventIdRoute
  '/organizations/$organizationSlug/calendar': typeof OrganizationsOrganizationSlugCalendarIndexRoute
  '/organizations/$organizationSlug/members': typeof OrganizationsOrganizationSlugMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRouteRouteWithChildren
  '/organizations': typeof OrganizationsRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/organizations/$organizationSlug': typeof OrganizationsOrganizationSlugRouteRouteWithChildren
  '/calendar/$eventId': typeof CalendarEventIdRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/calendar/': typeof CalendarIndexRoute
  '/organizations/$organizationSlug/calendar': typeof OrganizationsOrganizationSlugCalendarRouteRouteWithChildren
  '/organizations/$organizationSlug/': typeof OrganizationsOrganizationSlugIndexRoute
  '/organizations/$organizationSlug/calendar/$eventId': typeof OrganizationsOrganizationSlugCalendarEventIdRoute
  '/organizations/$organizationSlug/calendar/': typeof OrganizationsOrganizationSlugCalendarIndexRoute
  '/organizations/$organizationSlug/members/': typeof OrganizationsOrganizationSlugMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/organizations'
    | '/accept-invitation'
    | '/reset-password'
    | '/organizations/$organizationSlug'
    | '/calendar/$eventId'
    | '/organizations/new'
    | '/calendar/'
    | '/organizations/$organizationSlug/calendar'
    | '/organizations/$organizationSlug/'
    | '/organizations/$organizationSlug/calendar/$eventId'
    | '/organizations/$organizationSlug/calendar/'
    | '/organizations/$organizationSlug/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/organizations'
    | '/accept-invitation'
    | '/reset-password'
    | '/calendar/$eventId'
    | '/organizations/new'
    | '/calendar'
    | '/organizations/$organizationSlug'
    | '/organizations/$organizationSlug/calendar/$eventId'
    | '/organizations/$organizationSlug/calendar'
    | '/organizations/$organizationSlug/members'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/organizations'
    | '/accept-invitation'
    | '/reset-password'
    | '/organizations/$organizationSlug'
    | '/calendar/$eventId'
    | '/organizations/new'
    | '/calendar/'
    | '/organizations/$organizationSlug/calendar'
    | '/organizations/$organizationSlug/'
    | '/organizations/$organizationSlug/calendar/$eventId'
    | '/organizations/$organizationSlug/calendar/'
    | '/organizations/$organizationSlug/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRouteRoute: typeof CalendarRouteRouteWithChildren
  OrganizationsRouteRoute: typeof OrganizationsRouteRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof CalendarRouteRoute
    }
    '/calendar/$eventId': {
      id: '/calendar/$eventId'
      path: '/$eventId'
      fullPath: '/calendar/$eventId'
      preLoaderRoute: typeof CalendarEventIdRouteImport
      parentRoute: typeof CalendarRouteRoute
    }
    '/organizations/$organizationSlug': {
      id: '/organizations/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/organizations/$organizationSlug'
      preLoaderRoute: typeof OrganizationsOrganizationSlugRouteRouteImport
      parentRoute: typeof OrganizationsRouteRoute
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteImport
      parentRoute: typeof OrganizationsRouteRoute
    }
    '/organizations/$organizationSlug/': {
      id: '/organizations/$organizationSlug/'
      path: '/'
      fullPath: '/organizations/$organizationSlug/'
      preLoaderRoute: typeof OrganizationsOrganizationSlugIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationSlugRouteRoute
    }
    '/organizations/$organizationSlug/calendar': {
      id: '/organizations/$organizationSlug/calendar'
      path: '/calendar'
      fullPath: '/organizations/$organizationSlug/calendar'
      preLoaderRoute: typeof OrganizationsOrganizationSlugCalendarRouteRouteImport
      parentRoute: typeof OrganizationsOrganizationSlugRouteRoute
    }
    '/organizations/$organizationSlug/calendar/': {
      id: '/organizations/$organizationSlug/calendar/'
      path: '/'
      fullPath: '/organizations/$organizationSlug/calendar/'
      preLoaderRoute: typeof OrganizationsOrganizationSlugCalendarIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationSlugCalendarRouteRoute
    }
    '/organizations/$organizationSlug/calendar/$eventId': {
      id: '/organizations/$organizationSlug/calendar/$eventId'
      path: '/$eventId'
      fullPath: '/organizations/$organizationSlug/calendar/$eventId'
      preLoaderRoute: typeof OrganizationsOrganizationSlugCalendarEventIdRouteImport
      parentRoute: typeof OrganizationsOrganizationSlugCalendarRouteRoute
    }
    '/organizations/$organizationSlug/members/': {
      id: '/organizations/$organizationSlug/members/'
      path: '/members'
      fullPath: '/organizations/$organizationSlug/members/'
      preLoaderRoute: typeof OrganizationsOrganizationSlugMembersIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationSlugRouteRoute
    }
  }
}

interface CalendarRouteRouteChildren {
  CalendarEventIdRoute: typeof CalendarEventIdRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
}

const CalendarRouteRouteChildren: CalendarRouteRouteChildren = {
  CalendarEventIdRoute: CalendarEventIdRoute,
  CalendarIndexRoute: CalendarIndexRoute,
}

const CalendarRouteRouteWithChildren = CalendarRouteRoute._addFileChildren(
  CalendarRouteRouteChildren,
)

interface OrganizationsOrganizationSlugCalendarRouteRouteChildren {
  OrganizationsOrganizationSlugCalendarEventIdRoute: typeof OrganizationsOrganizationSlugCalendarEventIdRoute
  OrganizationsOrganizationSlugCalendarIndexRoute: typeof OrganizationsOrganizationSlugCalendarIndexRoute
}

const OrganizationsOrganizationSlugCalendarRouteRouteChildren: OrganizationsOrganizationSlugCalendarRouteRouteChildren =
  {
    OrganizationsOrganizationSlugCalendarEventIdRoute:
      OrganizationsOrganizationSlugCalendarEventIdRoute,
    OrganizationsOrganizationSlugCalendarIndexRoute:
      OrganizationsOrganizationSlugCalendarIndexRoute,
  }

const OrganizationsOrganizationSlugCalendarRouteRouteWithChildren =
  OrganizationsOrganizationSlugCalendarRouteRoute._addFileChildren(
    OrganizationsOrganizationSlugCalendarRouteRouteChildren,
  )

interface OrganizationsOrganizationSlugRouteRouteChildren {
  OrganizationsOrganizationSlugCalendarRouteRoute: typeof OrganizationsOrganizationSlugCalendarRouteRouteWithChildren
  OrganizationsOrganizationSlugIndexRoute: typeof OrganizationsOrganizationSlugIndexRoute
  OrganizationsOrganizationSlugMembersIndexRoute: typeof OrganizationsOrganizationSlugMembersIndexRoute
}

const OrganizationsOrganizationSlugRouteRouteChildren: OrganizationsOrganizationSlugRouteRouteChildren =
  {
    OrganizationsOrganizationSlugCalendarRouteRoute:
      OrganizationsOrganizationSlugCalendarRouteRouteWithChildren,
    OrganizationsOrganizationSlugIndexRoute:
      OrganizationsOrganizationSlugIndexRoute,
    OrganizationsOrganizationSlugMembersIndexRoute:
      OrganizationsOrganizationSlugMembersIndexRoute,
  }

const OrganizationsOrganizationSlugRouteRouteWithChildren =
  OrganizationsOrganizationSlugRouteRoute._addFileChildren(
    OrganizationsOrganizationSlugRouteRouteChildren,
  )

interface OrganizationsRouteRouteChildren {
  OrganizationsOrganizationSlugRouteRoute: typeof OrganizationsOrganizationSlugRouteRouteWithChildren
  OrganizationsNewRoute: typeof OrganizationsNewRoute
}

const OrganizationsRouteRouteChildren: OrganizationsRouteRouteChildren = {
  OrganizationsOrganizationSlugRouteRoute:
    OrganizationsOrganizationSlugRouteRouteWithChildren,
  OrganizationsNewRoute: OrganizationsNewRoute,
}

const OrganizationsRouteRouteWithChildren =
  OrganizationsRouteRoute._addFileChildren(OrganizationsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRouteRoute: CalendarRouteRouteWithChildren,
  OrganizationsRouteRoute: OrganizationsRouteRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
